<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.4" />
    <PackageReference Include="NSwag.AspNetCore" Version="14.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KtwAutomotiveEngineering.Api.V1\KtwAutomotiveEngineering.Api.V1.csproj" />
    <ProjectReference Include="..\KtwAutomotiveEngineering.Blazor\KtwAutomotiveEngineering.Blazor.csproj" />
    <ProjectReference Include="..\KtwAutomotiveEngineering.Shared\KtwAutomotiveEngineering.V1.Shared.csproj" />
  </ItemGroup>

</Project>
