<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.3" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\KtwAutomotiveEngineering.Entities\KtwAutomotiveEngineering.Entities.csproj" />
		<ProjectReference Include="..\KtwAutomotiveEngineering.Service.Contracts\KtwAutomotiveEngineering.Service.Contracts.csproj" />
		<ProjectReference Include="..\KtwAutomotiveEngineering.V1.Shared\KtwAutomotiveEngineering.V1.Shared.csproj" />
	</ItemGroup>

</Project>
